version: '3.8'

services:
  crawl4ai:
    image: unclecode/crawl4ai:latest
    container_name: crawl4ai-server
    ports:
      - "11235:11235"
    environment:
      - CRAWL4AI_API_TOKEN=12345
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - GEMINI_API_TOKEN=${GEMINI_API_TOKEN:-}
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173,http://127.0.0.1:3000,http://127.0.0.1:5173
      - CORS_ALLOW_CREDENTIALS=true
    volumes:
      - /dev/shm:/dev/shm
    shm_size: '1gb'
    restart: unless-stopped
    platform: linux/amd64  # 指定Intel CPU架构
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11235/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - crawl4ai-network

networks:
  crawl4ai-network:
    driver: bridge 